# Generated by Django 4.2.6 on 2023-11-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان الرئيسي')),
                ('slogan', models.TextField(verbose_name='الجملة الفرعية')),
                ('snapchat', models.TextField(blank=True, null=True, verbose_name='رابط سناب شات')),
                ('whatsapp', models.TextField(blank=True, null=True, verbose_name='رابط واتساب')),
                ('tiktok', models.TextField(blank=True, null=True, verbose_name='رابط تيكتوك')),
                ('location', models.TextField(blank=True, null=True, verbose_name='رابط لوكيشن')),
            ],
        ),
    ]
