# Generated by Django 5.0.1 on 2024-02-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyowner',
            name='a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
