# Generated by Django 5.0.1 on 2024-02-13 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyowner',
            name='data',
        ),
    ]
