# Generated by Django 5.0.1 on 2024-06-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_complain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complain',
            options={'managed': True, 'verbose_name': 'شكوى', 'verbose_name_plural': 'الشكاوي'},
        ),
    ]
