# Generated by Django 5.0.1 on 2024-02-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_remove_propertyowner_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyowner',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
