# Generated by Django 5.0.1 on 2024-02-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_home_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='slogan',
            field=models.TextField(blank=True, null=True, verbose_name='الجملة الفرعية'),
        ),
    ]
