# Generated by Django 5.0.1 on 2024-04-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=25, null=True)),
                ('whatsapp_tel', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'صفحة تفاصيل الإعلان',
                'verbose_name_plural': 'صفحة تفاصيل الإعلان',
            },
        ),
    ]
