# Generated by Django 5.0.1 on 2024-07-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_privacypolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'سياسة الخصوصية', 'verbose_name_plural': 'سياسة الخصوصية'},
        ),
    ]
