
# Generated by Django 4.2.6 on 2024-02-07 10:5
# Generated by Django 5.0.1 on 2024-02-07 10:53


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='sub_text',
            field=models.TextField(blank=True, null=True, verbose_name='النص الفرعي'),
        ),
    ]
