# Generated by Django 4.2.6 on 2023-11-10 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_favourite_profile_favourite_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'verbose_name': 'عنصر مفضلة', 'verbose_name_plural': 'قائمة المفضلة'},
        ),
    ]
