# Generated by Django 4.2.6 on 2023-11-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='رقم الجوال'),
            preserve_default=False,
        ),
    ]
