# Generated by Django 5.0.1 on 2024-03-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'مستخدم'), ('real_estate_marketer', 'مسوق عقاري'), ('real_estate_office', 'مكتب عقاري')], default='abdullah', max_length=200, verbose_name='نوع المستخدم'),
            preserve_default=False,
        ),
    ]
