# Generated by Django 4.2.6 on 2024-01-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fal_license',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/fal/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='office_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المكتب كما هو مكتوب في السجل التجاري'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('m', 'ذكر'), ('f', 'أنثى')], max_length=200, null=True, verbose_name='الجنس'),
        ),
    ]
