# Generated by Django 5.0.1 on 2024-03-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile/', verbose_name='صورة الملف الشخصي'),
        ),
    ]
