# Generated by Django 4.2.6 on 2024-01-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_commercial_registration_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number_verify_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
