# Generated by Django 4.2.6 on 2024-01-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_phone_number_verify_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'مستخدم'), ('real_estate_marketer', 'مسوق عقاري'), ('real_estate_office', 'مكتب عقاري')], max_length=200, null=True, verbose_name='نوع المستخدم'),
        ),
    ]
