# Generated by Django 5.0.1 on 2024-04-30 15:42

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم البرمجي')),
                ('display_name', models.CharField(max_length=100, verbose_name='الاسم الظاهر')),
            ],
            options={
                'verbose_name': 'قسم عقار',
                'verbose_name_plural': 'أقسام العقارات',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.IntegerField(blank=True, default=0, null=True)),
                ('rented', models.BooleanField(blank=True, default=False, null=True, verbose_name='تم التأجير')),
                ('sold', models.BooleanField(blank=True, default=False, null=True, verbose_name='تم البيع')),
                ('agree', models.BooleanField(default=False, verbose_name='موافقة')),
                ('lat', models.CharField(blank=True, max_length=200, null=True)),
                ('lng', models.CharField(blank=True, max_length=200, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإضافة')),
                ('p_type', models.CharField(blank=True, choices=[('apartment_rent', 'شقة للايجار'), ('floor_rent', 'دور للايجار'), ('villa_rent', 'فيلا للايجار'), ('shop_rent', 'محل للايجار'), ('resthouse_rent', 'استراحة للايجار'), ('commercial_office_rent', 'مكتب تجاري للايجار'), ('commercial_office_sale', 'مكتب تجاري للبيع'), ('land_rent', 'أرض للايجار'), ('building_rent', 'عمارة للايجار'), ('branch_rent', 'مستودع للايجار'), ('branch_sale', 'مستودع للبيع'), ('furnished_apartment_rent', 'شقة مفروشة للايجار'), ('chalet_rent', 'شاليه للايجار'), ('chalet_sale', 'شاليه للبيع'), ('land_sale', 'أرض للبيع'), ('villa_sale', 'فيلا للبيع'), ('apartment_sale', 'شقة للبيع'), ('building_sale', 'عمارة للبيع'), ('resthouse_sale', 'استراحة للبيع'), ('farm_sale', 'مزرعة للبيع'), ('shop_sale', 'محل للبيع'), ('floor_sale', 'دور للبيع')], max_length=250, null=True, verbose_name='نوع العقار')),
                ('sale', models.BooleanField(blank=True, default=False, null=True, verbose_name='للبيع')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الإعلان')),
                ('neighborhood', models.CharField(blank=True, max_length=250, null=True, verbose_name='الحي')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='المدينة')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الإعلان')),
                ('price', models.FloatField(default=0, verbose_name='السعر (ريال سعودي)')),
                ('space', models.IntegerField(default=0, verbose_name='المساحة (متر مربع)')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='العرض (متر)')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='الطول (متر)')),
                ('advertiser_relation', models.CharField(max_length=50, verbose_name='علاقة المعلن بالعقار')),
                ('exclusive', models.BooleanField(default=False, verbose_name='حصري')),
                ('video', models.FileField(blank=True, null=True, upload_to='rent/apartment/video', verbose_name='فيديو')),
                ('interface', models.CharField(blank=True, choices=[('شمالية', 'شمالية'), ('جنوبية', 'جنوبية'), ('غربية', 'غربية'), ('شرقية', 'شرقية'), ('شمالية شرقية', 'شمالية شرقية'), ('شمالية غربية', 'شمالية غربية'), ('جنوبية شرقية', 'جنوبية شرقية'), ('جنوبية غربية', 'جنوبية غربية')], max_length=100, null=True, verbose_name='الواجهة')),
                ('stores_count', models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='عدد المحلات')),
                ('apartments_count', models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='عدد الشقق')),
                ('street_width', models.FloatField(blank=True, null=True, verbose_name='عرض الشارع')),
                ('rooms', models.CharField(blank=True, max_length=10, null=True, verbose_name='الغرف')),
                ('lounges', models.CharField(blank=True, max_length=10, null=True, verbose_name='الصالات')),
                ('wells', models.CharField(blank=True, max_length=10, null=True, verbose_name='عدد الآبار')),
                ('trees', models.CharField(blank=True, max_length=10, null=True, verbose_name='عدد الأشجار')),
                ('bathroom', models.CharField(blank=True, max_length=10, null=True, verbose_name='عدد دورات المياه')),
                ('floor', models.CharField(blank=True, max_length=200, null=True, verbose_name='الدور')),
                ('property_age', models.CharField(blank=True, max_length=200, null=True, verbose_name='عمر العقار')),
                ('families', models.BooleanField(default=False, verbose_name='عوائل')),
                ('single', models.BooleanField(default=False, verbose_name='عزاب')),
                ('rent_type', models.CharField(blank=True, choices=[('yearly', 'سنوي'), ('monthly', 'شهري')], max_length=50, null=True, verbose_name='نوع الإيجار')),
                ('purpose', models.CharField(blank=True, max_length=100, null=True, verbose_name='الغرض')),
                ('description', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('furnished', models.BooleanField(default=False, verbose_name='مؤثثة')),
                ('kitchen', models.BooleanField(default=False, verbose_name='مطبخ')),
                ('extenstion', models.BooleanField(default=False, verbose_name='ملحق')),
                ('car_entrance', models.BooleanField(default=False, verbose_name='مدخل سيارة')),
                ('elevator', models.BooleanField(default=False, verbose_name='مصعد كهربائي')),
                ('ac', models.BooleanField(default=False, verbose_name='مكيف')),
                ('water_exist', models.BooleanField(default=False, verbose_name='توفر الماء')),
                ('power_exist', models.BooleanField(default=False, verbose_name='توفر الكهرباء')),
                ('sanitation_exist', models.BooleanField(default=False, verbose_name='توفر الصرف')),
                ('private_surface', models.BooleanField(default=False, verbose_name='سطح خاص')),
                ('in_villa', models.BooleanField(default=False, verbose_name='في فيلا')),
                ('two_enternace', models.BooleanField(default=False, verbose_name='مدخلين')),
                ('private_enternace', models.BooleanField(default=False, verbose_name='مدخل خاص')),
                ('driver_room', models.BooleanField(default=False, verbose_name='غرفة سائق')),
                ('maid_room', models.BooleanField(default=False, verbose_name='غرفة خادمة')),
                ('duplex', models.BooleanField(default=False, verbose_name='دوبلكس')),
                ('basement', models.BooleanField(default=False, verbose_name='قبو')),
                ('yard', models.BooleanField(default=False, verbose_name='حوش')),
                ('pool', models.BooleanField(default=False, verbose_name='مسبح')),
                ('football_field', models.BooleanField(default=False, verbose_name='ملعب كرة قدم')),
                ('volly_field', models.BooleanField(default=False, verbose_name='ملعب كرة طائرة')),
                ('hair_tent_house', models.BooleanField(default=False, verbose_name='بيت شعر')),
                ('amusement', models.BooleanField(default=False, verbose_name='ملاهي')),
                ('family_part', models.BooleanField(default=False, verbose_name='قسم عوائل')),
                ('monthly_payment', models.BooleanField(default=False, verbose_name='دفع شهري')),
                ('quarterly_payment', models.BooleanField(default=False, verbose_name='دفع ربع سنوي')),
                ('semi_annual_payment', models.BooleanField(default=False, verbose_name='دفع نصف سنوي')),
                ('annual_payment', models.BooleanField(default=False, verbose_name='دفع سنوي')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عقار',
                'verbose_name_plural': 'عقارات',
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
            options={
                'verbose_name': 'المفضلة',
                'verbose_name_plural': 'المفضلة',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='property/images/')),
                ('main', models.BooleanField(blank=True, default=0, null=True, verbose_name='صورة رئيسية')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='property.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'صورة عقار',
                'verbose_name_plural': 'صور العقارات',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=40, verbose_name='رقم الإعلان')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property', verbose_name='الإعلان')),
            ],
            options={
                'verbose_name': 'إبلاغ',
                'verbose_name_plural': 'البلاغات',
            },
        ),
    ]
