# Generated by Django 4.2.6 on 2023-10-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.CharField(blank=True, choices=[('apartment_rent', 'شقة للايجار'), ('floor_rent', 'دور للايجار'), ('villa_rent', 'فيلا للايجار'), ('shop_rent', 'محل للايجار'), ('resthouse_rent', 'استراحة للايجار'), ('commercial_office_rent', 'مكتب تجاري للايجار'), ('land_rent', 'أرض للايجار'), ('building_rent', 'عمارة للايجار'), ('branch_rent', 'مستودع للايجار'), ('furnished_apartment_rent', 'شقة مفروشة للايجار'), ('chalet_rent', 'شاليه للايجار')], max_length=250, null=True, verbose_name='نوع العقار')),
                ('sale', models.BooleanField(blank=True, default=False, null=True, verbose_name='للبيع')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الإعلان')),
                ('neighborhood', models.CharField(blank=True, max_length=250, null=True, verbose_name='الحي')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='المدينة')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الإعلان')),
                ('price', models.IntegerField(default=0, verbose_name='السعر (ريال سعودي)')),
                ('space', models.IntegerField(default=0, verbose_name='المساحة (متر مربع)')),
                ('advertiser_relation', models.CharField(max_length=50, verbose_name='علاقة المعلن بالعقار')),
                ('exclusive', models.BooleanField(default=False, verbose_name='حصري')),
                ('video', models.FileField(blank=True, null=True, upload_to='rent/apartment/video', verbose_name='فيديو')),
                ('street_width', models.FloatField(blank=True, null=True, verbose_name='عرض الشارع')),
                ('rooms', models.CharField(blank=True, max_length=10, null=True, verbose_name='الغرف')),
                ('lounges', models.CharField(blank=True, max_length=10, null=True, verbose_name='الصالات')),
                ('bathroom', models.CharField(blank=True, max_length=10, null=True, verbose_name='عدد دورات المياه')),
                ('floor', models.CharField(blank=True, max_length=200, null=True, verbose_name='الدور')),
                ('property_age', models.CharField(blank=True, max_length=200, null=True, verbose_name='عمر العقار')),
                ('families', models.BooleanField(default=True, verbose_name='عوائل ام عزاب')),
                ('rent_type', models.CharField(blank=True, choices=[('yearly', 'سنوي'), ('monthly', 'شهري')], max_length=50, null=True, verbose_name='نوع الإيجار')),
                ('description', models.TextField(blank=True, default='   ', null=True, verbose_name='وصف العقار')),
                ('furnished', models.BooleanField(default=False, verbose_name='مؤثثة')),
                ('kitchen', models.BooleanField(default=False, verbose_name='مطبخ')),
                ('extenstion', models.BooleanField(default=False, verbose_name='ملحق')),
                ('car_entrance', models.BooleanField(default=False, verbose_name='مدخل سيارة')),
                ('elevator', models.BooleanField(default=False, verbose_name='مصعد كهربائي')),
                ('ac', models.BooleanField(default=False, verbose_name='مكيف')),
                ('water_exist', models.BooleanField(default=False, verbose_name='توفر الماء')),
                ('power_exist', models.BooleanField(default=False, verbose_name='توفر الكهرباء')),
                ('sanitation_exist', models.BooleanField(default=False, verbose_name='توفر الصرف')),
                ('private_surface', models.BooleanField(default=False, verbose_name='سطح خاص')),
                ('in_villa', models.BooleanField(default=False, verbose_name='في فيلا')),
                ('two_enternace', models.BooleanField(default=False, verbose_name='مدخلين')),
                ('private_enternace', models.BooleanField(default=False, verbose_name='مدخل خاص')),
            ],
        ),
    ]
