# Generated by Django 4.2.6 on 2023-10-27 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'عقار', 'verbose_name_plural': 'عقارات'},
        ),
        migrations.AddField(
            model_name='property',
            name='amusement',
            field=models.BooleanField(default=False, verbose_name='ملاهي'),
        ),
        migrations.AddField(
            model_name='property',
            name='apartments_count',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='عدد الشقق'),
        ),
        migrations.AddField(
            model_name='property',
            name='basement',
            field=models.BooleanField(default=False, verbose_name='قبو'),
        ),
        migrations.AddField(
            model_name='property',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AddField(
            model_name='property',
            name='driver_room',
            field=models.BooleanField(default=False, verbose_name='غرفة سائق'),
        ),
        migrations.AddField(
            model_name='property',
            name='duplex',
            field=models.BooleanField(default=False, verbose_name='دوبلكس'),
        ),
        migrations.AddField(
            model_name='property',
            name='family_part',
            field=models.BooleanField(default=False, verbose_name='قسم عوائل'),
        ),
        migrations.AddField(
            model_name='property',
            name='football_field',
            field=models.BooleanField(default=False, verbose_name='ملعب كرة قدم'),
        ),
        migrations.AddField(
            model_name='property',
            name='hair_tent_house',
            field=models.BooleanField(default=False, verbose_name='بيت شعر'),
        ),
        migrations.AddField(
            model_name='property',
            name='interface',
            field=models.CharField(blank=True, choices=[('شمالية', 'شمالية'), ('جنوبية', 'جنوبية'), ('غربية', 'غربية'), ('شرقية', 'شرقية'), ('شمالية شرقية', 'شمالية شرقية'), ('شمالية غربية', 'شمالية غربية'), ('جنوبية شرقية', 'جنوبية شرقية'), ('جنوبية غربية', 'جنوبية غربية')], max_length=100, null=True, verbose_name='الواجهة'),
        ),
        migrations.AddField(
            model_name='property',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='الطول (متر)'),
        ),
        migrations.AddField(
            model_name='property',
            name='maid_room',
            field=models.BooleanField(default=False, verbose_name='غرفة خادمة'),
        ),
        migrations.AddField(
            model_name='property',
            name='pool',
            field=models.BooleanField(default=False, verbose_name='مسبح'),
        ),
        migrations.AddField(
            model_name='property',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الغرض'),
        ),
        migrations.AddField(
            model_name='property',
            name='sotres_count',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='عدد المحلات'),
        ),
        migrations.AddField(
            model_name='property',
            name='volly_field',
            field=models.BooleanField(default=False, verbose_name='ملعب كرة طائرة'),
        ),
        migrations.AddField(
            model_name='property',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='العرض (متر)'),
        ),
        migrations.AddField(
            model_name='property',
            name='yard',
            field=models.BooleanField(default=False, verbose_name='حوش'),
        ),
        migrations.AlterField(
            model_name='property',
            name='p_type',
            field=models.CharField(blank=True, choices=[('apartment_rent', 'شقة للايجار'), ('floor_rent', 'دور للايجار'), ('villa_rent', 'فيلا للايجار'), ('shop_rent', 'محل للايجار'), ('resthouse_rent', 'استراحة للايجار'), ('commercial_office_rent', 'مكتب تجاري للايجار'), ('land_rent', 'أرض للايجار'), ('building_rent', 'عمارة للايجار'), ('branch_rent', 'مستودع للايجار'), ('furnished_apartment_rent', 'شقة مفروشة للايجار'), ('chalet_rent', 'شاليه للايجار'), ('land_sale', 'أرض للبيع'), ('villa_sale', 'فيلا للبيع'), ('apartment_sale', 'شقة للبيع'), ('building_sale', 'عمارة للبيع'), ('resthouse_sale', 'استراحة للبيع'), ('farm_sale', 'مزرعة للبيع'), ('shop_sale', 'محل للبيع'), ('floor_sale', 'دور للبيع')], max_length=250, null=True, verbose_name='نوع العقار'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='property/images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
