# Generated by Django 5.0.1 on 2024-03-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rented',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='تم التأجير'),
        ),
        migrations.AddField(
            model_name='property',
            name='sold',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='تم البيع'),
        ),
    ]
