# Generated by Django 5.0.1 on 2024-04-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_rented_property_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='visits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
