# Generated by Django 4.2.6 on 2023-11-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_options_property_amusement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='main',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='صورة رئيسية'),
        ),
    ]
