# Generated by Django 5.0.1 on 2024-06-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_fal_number_property_license_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='pin',
            field=models.BooleanField(default=0, verbose_name='مثبت'),
        ),
    ]
