# Generated by Django 5.0.1 on 2024-07-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='مسودة'),
        ),
    ]
