# Generated by Django 5.0.1 on 2024-08-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='watermarks')),
            ],
            options={
                'verbose_name': 'علامة مائية',
                'verbose_name_plural': 'علامات مائية',
            },
        ),
    ]
