# Generated by Django 4.2.6 on 2023-11-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_lat_property_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='sotres_count',
            new_name='stores_count',
        ),
    ]
