# Generated by Django 4.2.6 on 2023-11-08 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_property_user_property_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'verbose_name': 'صورة عقار', 'verbose_name_plural': 'صور العقارات'},
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='property.property', verbose_name='العقار'),
        ),
    ]
