# Generated by Django 4.2.6 on 2023-11-25 07:36

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_remove_property_profile_property_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
