# Generated by Django 4.2.6 on 2023-11-28 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='number',
            field=models.CharField(default='', max_length=40, verbose_name='رقم الإعلان'),
        ),
        migrations.AlterField(
            model_name='report',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property', verbose_name='الإعلان'),
        ),
    ]
