# Generated by Django 4.2.6 on 2023-11-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_report_number_alter_report_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agree',
            field=models.BooleanField(default=False, verbose_name='موافقة'),
        ),
    ]
