# Generated by Django 4.2.6 on 2023-12-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_property_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='families_or_single',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='عوائل / عزاب'),
        ),
    ]
