# Generated by Django 4.2.6 on 2023-12-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_property_families_or_single'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='families_or_single',
        ),
        migrations.AddField(
            model_name='property',
            name='single',
            field=models.BooleanField(default=False, verbose_name='عزاب'),
        ),
    ]
