# Generated by Django 4.2.6 on 2023-12-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_remove_property_families_or_single_property_single'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='annual_payment',
            field=models.BooleanField(default=False, verbose_name='دفع سنوي'),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_payment',
            field=models.BooleanField(default=False, verbose_name='دفع شهري'),
        ),
        migrations.AddField(
            model_name='property',
            name='quarterly_payment',
            field=models.BooleanField(default=False, verbose_name='دفع ربع سنوي'),
        ),
        migrations.AddField(
            model_name='property',
            name='semi_annual_payment',
            field=models.BooleanField(default=False, verbose_name='دفع نصف سنوي'),
        ),
    ]
