# Generated by Django 4.2.6 on 2024-01-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_property_annual_payment_property_monthly_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.FloatField(default=0, verbose_name='السعر (ريال سعودي)'),
        ),
    ]
