# Generated by Django 4.2.6 on 2024-01-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_alter_property_p_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='trees',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='عدد الأشجار'),
        ),
        migrations.AddField(
            model_name='property',
            name='wells',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='عدد الآبار'),
        ),
    ]
