# Generated by Django 4.2.6 on 2024-01-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_property_trees_property_wells'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='families',
            field=models.BooleanField(default=False, verbose_name='عوائل ام عزاب'),
        ),
    ]
