# Generated by Django 4.2.6 on 2024-01-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_alter_property_families'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم البرمجي')),
                ('display_name', models.CharField(max_length=100, verbose_name='الاسم الظاهر')),
            ],
        ),
    ]
