# Generated by Django 4.2.6 on 2024-01-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_alter_propertydepartment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='families',
            field=models.BooleanField(default=False, verbose_name='عوائل'),
        ),
    ]
